### ISSUE TITLE
Internal error (to do with sorting/serializing)

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#472]
http://pastebin.com/MpqpLzzJ

Extractions:-
2017-01-11 08:24:46,246 :Traceback (most recent call last):
2017-01-11 08:24:46,246 :  File "/home/ngoonee/.local/lib/python3.5/site-packages/beancount_fava-1.3.dev0-py3.5.egg/fava/core/charts.py", line 32, in default
2017-01-11 08:24:46,246 :    return JSONEncoder.default(self, o)
2017-01-11 08:24:46,246 :  File "/usr/local/lib/python3.5/dist-packages/flask/json.py", line 83, in default
2017-01-11 08:24:46,246 :    return _json.JSONEncoder.default(self, o)
2017-01-11 08:24:46,246 :  File "/usr/local/lib/python3.5/dist-packages/simplejson/encoder.py", line 252, in default
2017-01-11 08:24:46,246 :    raise TypeError(repr(o) + " is not JSON serializable")
2017-01-11 08:24:46,246 :TypeError: <beancount.core.display_context.DisplayContext object at 0x7f43e30ffa58> is not JSON serializable
  File "/home/ngoonee/.local/lib/python3.5/site-packages/beancount_fava-1.3.dev0-py3.5.egg/fava/core/charts.py", line 34, in default
    return str(o)
  File "/home/ngoonee/.local/lib/python3.5/site-packages/beancount-2.0b13-py3.5-linux-x86_64.egg/beancount/core/display_context.py", line 190, in __str__
    for currency, ccontext in sorted(self.ccontexts.items()):
TypeError: unorderable types: type() < str()

**Comment by yagebu** [comment]
Seems to be this (resolved) [issue](https://bitbucket.org/blais/beancount/issues/139/typeerror-in-coredisplay_context) in Beancount. Can you try updating Beancount to see if it persists?

**Comment by ngoonee** [comment]
I think I updated at the same time. Will check again later.

**Comment by ngoonee** [comment]
Yes I'm fully up to date both with fava and beancount. Do I raise the issue with beancount?

**Comment by ngoonee** [comment]
Found the offending transaction, commented it in the Beancount issue. For completeness, I had:-

2017-01-01 * "" "Dinner"
    Expenses:Food:EatingOut 42
    Assets:Banking:PBB:VisaSignature

And similar, all missing currency. Pretty sure 'operating_currency' is supposed to handle that, but adding the currency 'fixed' it. Suspect something has changed in beancount's handling.

**Comment by adamgibbins** [comment]
> Pretty sure 'operating_currency' is supposed to handle that

It's not, that variable is only there to define the primary currencies in reporting. It's not meant to be a default.

**Comment by ngoonee** [comment]
On Thu, Jan 12, 2017 at 3:58 AM, Adam Gibbins <notifications@github.com>
wrote:

> Pretty sure 'operating_currency' is supposed to handle that
>
> It's not, that variable is only there to define the primary currencies in
> reporting. It's not meant to be a default.
>
Oh, that's news to me, thanks. Is this expected behaviour then? Because if
it is then the new transaction adding mechanism should enforce it.

**Comment by yagebu** [comment]
> Is this expected behaviour then?

The transaction you wrote above is not valid, so it should throw an error (but not crash Beancount/Fava).

> Because if it is then the new transaction adding mechanism should enforce it.

That's not really possible at the moment as the two different booking modes allow for very different transactions.

**Comment by blais** [comment]
I think this has been fixed recently.
This is how the latest handles this:

/private/tmp/t.beancount:4:       Failed to categorize posting 0

   2017-01-01 * "Dinner"
     Expenses:Food:EatingOut           42 <class
'beancount.core.number.MISSING'>
     Assets:Banking:PBB:VisaSignature

Maybe I should cut another beta release.

**Comment by ngoonee** [comment]
I just updated beancount from hg and fava from git, it no longer crashes totally but it still does not show the previous behavior of just showing an error and allowing me to continue.

In particular, I can't even load the editor screen to fix the error. Same error of TypeError: '<' not supported between instances of 'type' and 'str'

**Comment by blais** [comment]
On Mon, Jan 16, 2017 at 3:37 PM, Ng Oon-Ee <notifications@github.com> wrote:

> I just updated beancount from hg and fava from git, it no longer crashes
> totally but it still does not show the previous behavior of just showing an
> error and allowing me to continue.
>
Beancount skips the offending postings when that happens, but continues
with all the other data.
Do you think it would be better for it to fail?


> In particular, I can't even load the editor screen to fix the error. Same
> error of TypeError: '<' not supported between instances of 'type' and 'str'
>
This is probably on the Fava side of things; I don't know what you mean by
"the editor".

**Comment by ngoonee** [comment]
@blais yes the error is on the Fava side of things. I realize as its' all hosted together here it can be a bit confusing, but my summary so far is:-

1. The error mentioned here happens whenever currency unit is not included. This is probably correct behavior ('probably' because I'm not really sure, myself).
2. It prevents fava from loading any screen. This is not the case with other errors. For example if I have a transaction that post-dates an account's closing date, fava can still load screens, including the editor screen which would allow me to edit the beancount file.

My issue is the fava behavior mentioned in 2 rather than the beancount behavior mentioned in 1.

**Comment by yagebu** [comment]
This is an error in Beancount (although Fava could handle it better and still render the page).

@blais: In this [line](https://bitbucket.org/blais/beancount/src/addfb38c947394997fa315fda9730c3a0425fb3f/src/python/beancount/core/display_context.py?at=default&fileviewer=file-view-default#display_context.py-190) (where Beancount renders the `DisplayContext` to a string) it tries to sort the dict of currencies to `_CurrencyContext`s. That's fine if all the currencies are strings, but in this case a `_CurrencyContext` for `beancount.core.number.MISSING` has been generated which causes the TypeErrror as the index is of type `type` and not `str`. Either `DisplayContext.__str__` should handle this case or this `_CurrencyContext` should be prevented from being created in the first place.

**Comment by blais** [comment]
Awesome, thanks for the report.
https://bitbucket.org/blais/beancount/issues/156/internal-error-to-do-with-sorting
